### ISSUE TITLE
Background Knowledge & Build System

### ISSUE THREAD

**Issue by mkohlhaas** [ed-apostol/InvictusChess#1]
Hi Edsel,

thanks a lot for sharing your code.

This seems like the most interesting open source chess engine I could find on CCRL.

Two quick questions:
1. What does it need to understand the code for an absolute novice in chess engine programming? I mean will the standard [wiki for chess programming](https://www.chessprogramming.org/) be sufficient? It seems your code uses the latest technology which might not be easily available.
2. Do you have a make file or something like that for this project?

Thanks and best regards!

**Comment by ed-apostol** [comment]
Hi Michael, chess programming wiki is the best resource. I've added a CMakeLists for the project that you can use in various IDEs.

**Comment by mkohlhaas** [comment]
Thanks a lot! Wow!
