### ISSUE TITLE
compile on Linux ?

### ISSUE THREAD

**Issue by tissatussa** [ed-apostol/InvictusChess#2]
i expect to compile your engine by gcc main.cpp but it has errors .. what's wrong ?  I use Xubuntu 20.04

**Comment by ed-apostol** [comment]
Hi Roelof, I've added Linux support in the code.

**Comment by tissatussa** [comment]
i tried to compile the newest source but i did not succeed .. i see no MakeFile, so i tried like this :

![Screenshot_2021-05-05_09-58-14](https://user-images.githubusercontent.com/1109281/117112080-d4a9fe00-ad88-11eb-8ee2-4bdb309594f7.png)

btw. you could leave this issue open until it is solved .. i can guide you while compiling on my Xubuntu 20.04 .. i'm not a beginner with Linux, i can supply more info about my environment etc.

**Comment by ed-apostol** [comment]
Try to comment out this line in that file:

#define USE_PEXT

**Comment by tissatussa** [comment]
i still get errors .. i only find that line in attacks.cpp and i commented it out like you said .. then i did :

`gcc *.cpp -o mychessengine 2> log.txt`

log.txt see [log.zip](https://github.com/ed-apostol/InvictusChess/files/6425832/log.zip)

**Comment by tissatussa** [comment]
does my gcc version matter ?

```
$ gcc --version
gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
```

**Comment by ed-apostol** [comment]
Can you try to add this header on the files that has errors:

#include <cstring>

**Comment by tissatussa** [comment]
you tell me which files have errors ? see log.txt

**Comment by tissatussa** [comment]
i'm not a C programmer, but is only "#include" sufficient ?  Would there be a file parameter ?

**Comment by ed-apostol** [comment]
I have included a CMakeLists.txt in the root directory that you can use. In the commandline, go to that root directory where CMakeLists.txt is, then try to run these:

mkdir build-dir
cd build-dir
cmake ..
make

Sorry I don't have a Linux machine to test this, I just merged someone's Linux code changes on an earlier version of Invictus.

**Comment by tissatussa** [comment]
thanks .. i recognise these code lines .. indeed i compiled my first Invictus binairy but it's invalid :

`Illegal instruction (core dumped)`

and i have a lot of warnings : see [make_invictus.zip](https://github.com/ed-apostol/InvictusChess/files/6426479/make_invictus.zip)

how can i create a full debug log for you ?

**Comment by tissatussa** [comment]
the illegal instruction error is because my CPU can not handle your code .. something with SSE BMI2 AVX POPCNT i don't know those settings .. do you ?  I encounter many engines on GitHub which detect such user system settings / properties and compile accordingly ..

**Comment by ed-apostol** [comment]
In bitutils.cpp uncomment this:

//#define NOPOPCNT

Also in attacks.cpp comment out:

#define USE_PEXT

It will then use the most primitive build. 

In CMakeLists.txt you can remove the "-Wall" text to reduce warnings.

**Comment by tissatussa** [comment]
? i already uncommented define USE_PEXT in attacks.cpp as you wrote .. and in my bitutils.cpp the line define NOPOPCNT was already commented out (by you?) .. im stuck

**Comment by ed-apostol** [comment]
I mean define it. Remove the //. Sorry for the confusion.

**Comment by tissatussa** [comment]
mmm .. same result :

`Illegal instruction (core dumped)`

**Comment by tissatussa** [comment]
here's my output of cmake .. :

$ cmake ..
-- The CXX compiler identification is GNU 10.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/roelof/Downloads/tmp6/InvictusChess_1/build-dir

**Comment by ed-apostol** [comment]
May I know what's your CPU?

In the CMakeLists.txt you can try removing some flags here: 
set (CMAKE_CXX_FLAGS "-Wall -O3 -msse3 -mpopcnt -mbmi2 -DNDEBUG")

Try removing -mbmi2, and -mpopcnt, etc

**Comment by tissatussa** [comment]
first i give you this output on my Linux :

$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 2993.104
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5188.04
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 2993.103
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5188.04
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 2993.102
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5188.04
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 2993.103
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 5188.04
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

**Comment by tissatussa** [comment]
the latest source code (r391 by git clone) does compile without errors now.
i did `cmake .` and then `make` and i got a valid Linux binary which runs fine in CuteChess.
[ i'm on Xubuntu 22.04 ]
